### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by hendriks73** [c0cky/TensorFlow-in-a-Nutshell#2]
Very useful series it seems—unfortunately though, your website is down, which is why I cannot access all parts:

<img width="755" alt="screen shot 2017-01-13 at 08 53 35" src="https://cloud.githubusercontent.com/assets/4749755/21922256/f228593e-d96d-11e6-9d8f-214f3b960e03.png">

Cheers!

**Comment by camrongodbout** [comment]
My apologies, the I host it on a little server and it sometimes gets choked up :/ I have restarted the server and the site should be back up! Thank you for letting me know!
